// Cross-implementation validation: prove that the TS loadSigner seed->ML-DSA-87 key
// derivation is byte-compatible with the Go reference (filippo.io/mldsa backed by
// FIPS 204 ML-DSA-87) for the same 32-byte seed.
//
// Context: keys-env.ts loadSigner splits a 64-byte secret as
//   ed25519 seed(32) || ML-DSA-87 seed(32)
// and calls ml_dsa87.keygen(seed32) from @noble/post-quantum to derive the keypair.
// The Go reference MarshalSigner stores the same layout and ParseSigner calls
// mldsa.NewPrivateKey(MLDSA87(), seed32) from filippo.io/mldsa.  Both must implement
// FIPS 204 KeyGen_internal identically.  A divergence here means the engine would
// produce signatures that the Go reader rejects (or vice-versa), silently breaking
// archive verification.
//
// This file pins three vectors generated by the Go helper
// cmd/gen-mldsa-seed-kat/main.go (run once; output committed to
// test/vectors/mldsa-seed-kat/kat.json):
//   seed1 (0x01 * 32) - fixed, fully deterministic
//   seed2 (0x02 * 32) - checks the mapping is not a constant function
//   seed3 (random)    - arbitrary seed round-trip with Go-produced signature
//
// Run with: node test/validate-mldsa-seed.ts

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { b64urlDecode, b64urlEncode } from "../src/crypto/bytes.ts";
import { mldsaKeygen, mldsaSign, mldsaVerify } from "../src/crypto/pq.ts";
import { loadSigner, verifierFrom } from "../src/keys-env.ts";
import { hybridSign, hybridVerify } from "../src/crypto/sign.ts";
import { concat } from "../src/crypto/bytes.ts";

const here = dirname(fileURLToPath(import.meta.url));
const katPath = join(here, "vectors", "mldsa-seed-kat", "kat.json");

let failures = 0;

function ok(label: string, cond: boolean): void {
  console.log(cond ? `  ok   ${label}` : `  FAIL ${label}`);
  if (!cond) failures++;
}

function check(label: string, got: string, want: string): void {
  const pass = got === want;
  console.log(pass ? `  ok   ${label}` : `  FAIL ${label}\n        got  ${got.slice(0, 64)}...\n        want ${want.slice(0, 64)}...`);
  if (!pass) failures++;
}

async function main(): Promise<void> {
  const kat = JSON.parse(readFileSync(katPath, "utf8")) as {
    seed: string;
    publicKey: string;
    secretKeySeed: string;
    message: string;
    signature: string;
    seed2: string;
    publicKey2: string;
    seed3: string;
    publicKey3: string;
    message3: string;
    signature3: string;
  };

  // -----------------------------------------------------------------------
  // Section 1: seed->public-key derivation matches the Go reference.
  // -----------------------------------------------------------------------
  console.log("mldsa-seed-kat (noble seed->pubkey agrees with Go filippo.io/mldsa):");

  const seed1 = b64urlDecode(kat.seed);
  const kp1 = mldsaKeygen(seed1);
  check("seed1: noble publicKey matches Go", b64urlEncode(kp1.publicKey), kat.publicKey);

  // Negative control: seed2 produces a DIFFERENT public key than seed1.
  const seed2 = b64urlDecode(kat.seed2);
  const kp2 = mldsaKeygen(seed2);
  check("seed2: noble publicKey matches Go", b64urlEncode(kp2.publicKey), kat.publicKey2);
  ok("seed1 and seed2 produce distinct public keys (not a constant function)", b64urlEncode(kp1.publicKey) !== b64urlEncode(kp2.publicKey));

  // -----------------------------------------------------------------------
  // Section 2: noble verifies a Go-produced DETERMINISTIC signature.
  // -----------------------------------------------------------------------
  // The Go helper used SignDeterministic (no hedging randomness), so the
  // signature is reproducible.  Noble must accept it.
  console.log("mldsa-seed-kat (noble verifies Go-signed deterministic signature):");

  const msg1 = b64urlDecode(kat.message);
  const goSig1 = b64urlDecode(kat.signature);
  ok("noble.verify(Go pub1, msg, Go deterministic sig1)", mldsaVerify(kp1.publicKey, msg1, goSig1));

  // Negative control: Go sig1 must NOT verify under the wrong key.
  ok("Go sig1 rejects wrong public key (seed2 key)", !mldsaVerify(kp2.publicKey, msg1, goSig1));
  // Negative control: Go sig1 must NOT verify for a different message.
  const wrongMsg = new TextEncoder().encode("this is not the signed message");
  ok("Go sig1 rejects wrong message", !mldsaVerify(kp1.publicKey, wrongMsg, goSig1));

  // -----------------------------------------------------------------------
  // Section 3: arbitrary-seed round-trip with Go-produced key and signature.
  // -----------------------------------------------------------------------
  // seed3 is a random 32-byte seed chosen by the Go helper.  Noble must
  // derive the same public key and accept the Go-produced signature.
  console.log("mldsa-seed-kat (arbitrary Go seed round-trip):");

  const seed3 = b64urlDecode(kat.seed3);
  const kp3 = mldsaKeygen(seed3);
  check("seed3: noble publicKey matches Go", b64urlEncode(kp3.publicKey), kat.publicKey3);

  const msg3 = b64urlDecode(kat.message3);
  const goSig3 = b64urlDecode(kat.signature3);
  ok("noble.verify(Go pub3, msg3, Go deterministic sig3)", mldsaVerify(kp3.publicKey, msg3, goSig3));

  // Negative control: sig3 must reject the message from vector 1.
  ok("Go sig3 rejects a message it was not signed over", !mldsaVerify(kp3.publicKey, msg1, goSig3));

  // -----------------------------------------------------------------------
  // Section 4: noble sign -> noble verify (engine sign-path self-consistency).
  // -----------------------------------------------------------------------
  // A noble-produced signature over the same message must also verify,
  // confirming the library is functional end-to-end and not just accepting
  // everything (vacuous-verify guard).
  console.log("mldsa-seed-kat (noble sign -> noble verify self-consistency):");

  const nobleSig1 = mldsaSign(kp1.secretKey, msg1);
  ok("noble sign/verify round-trip with seed1 keypair", mldsaVerify(kp1.publicKey, msg1, nobleSig1));

  // Noble self-signature must NOT verify under the seed2 key.
  ok("noble sig1 rejects wrong key (seed2)", !mldsaVerify(kp2.publicKey, msg1, nobleSig1));

  // Noble self-signature length must be 4627 bytes (FIPS 204 ML-DSA-87).
  ok("noble signature is 4627 bytes (ML-DSA-87 FIPS 204)", nobleSig1.length === 4627);

  // -----------------------------------------------------------------------
  // Section 5: loadSigner (keys-env.ts) wires the seed into the engine
  //            Signer struct correctly.
  // -----------------------------------------------------------------------
  // loadSigner accepts a base64url-encoded 64-byte value:
  //   first 32 bytes = ed25519 seed
  //   last  32 bytes = ML-DSA-87 seed
  // We use a fixed ed25519 seed (all-0x03) concatenated with seed1 so the
  // ML-DSA-87 half is the vector we already validated above.
  console.log("mldsa-seed-kat (loadSigner derives correct ML-DSA-87 public key):");

  const edSeed = new Uint8Array(32).fill(0x03);
  const combined64 = concat(edSeed, seed1);
  const combined64b64 = b64urlEncode(combined64);

  const signer = await loadSigner(combined64b64);
  // mldsaPublic from loadSigner must match what mldsaKeygen(seed1) produced.
  check("loadSigner.mldsaPublic matches Go-derived public key", b64urlEncode(signer.mldsaPublic), kat.publicKey);

  // The signer must produce a hybrid signature that verifies.
  const hybridMsg = new TextEncoder().encode("loadSigner hybrid sign/verify smoke-test");
  const hybridSig = await hybridSign(signer.edPrivate, signer.mldsaSecret, hybridMsg);
  const verifier = verifierFrom(signer);
  ok("loadSigner hybrid sign/verify round-trip", await hybridVerify(verifier, hybridMsg, hybridSig));

  // Hybrid signature must be at least 64 + 4627 = 4691 bytes.
  ok("hybrid signature is 4691 bytes (ed64 + mldsa4627)", hybridSig.length === 4691);

  // The ML-DSA half of the hybrid signature must verify under the Go-derived
  // public key (confirms the engine's signer would be verifiable by the Go
  // reader using the same key).
  const mldsaHalf = hybridSig.subarray(64);
  ok("ML-DSA half of hybrid sig verifies under Go-derived public key", mldsaVerify(signer.mldsaPublic, hybridMsg, mldsaHalf));

  // Hybrid signature must be rejected if the ML-DSA half is stripped
  // (prevents post-quantum downgrade; both halves are required).
  const edOnlySig = hybridSig.subarray(0, 64);
  ok("hybrid sig with ML-DSA half stripped is rejected (no PQ downgrade)", !(await hybridVerify(verifier, hybridMsg, edOnlySig)));

  // -----------------------------------------------------------------------
  // Section 6: hybridVerify is strictly boolean under a malformed
  //            verifier or signature. noble's ml_dsa87.verify THROWS on a
  //            wrong-length ML-DSA public key, and Web Crypto importKey
  //            rejects a wrong-length Ed25519 key; parseVerifier does not
  //            length-check the ML-DSA half, so hybridVerify must absorb any
  //            such error and return false (never throw), matching its
  //            documented contract and the Go reader's typed-error behaviour.
  // -----------------------------------------------------------------------
  console.log("hybridVerify boolean contract under malformed input:");

  // mustReturnFalse runs hybridVerify and fails the assertion if it throws OR
  // returns true; only a clean `false` passes. This is what distinguishes the
  // fixed behaviour (false) from the pre-fix behaviour (an escaping throw).
  const mustReturnFalse = async (label: string, v: { ed: Uint8Array; mldsa: Uint8Array }, message: Uint8Array, signature: Uint8Array): Promise<void> => {
    let result: boolean | "threw";
    try {
      result = await hybridVerify(v, message, signature);
    } catch {
      result = "threw";
    }
    ok(label, result === false);
  };

  // A wrong-length ML-DSA public key is the case noble throws on (length != 2592).
  await mustReturnFalse("short ML-DSA public key returns false, not throw", { ed: verifier.ed, mldsa: new Uint8Array(100) }, hybridMsg, hybridSig);
  await mustReturnFalse("long ML-DSA public key returns false, not throw", { ed: verifier.ed, mldsa: new Uint8Array(3000) }, hybridMsg, hybridSig);
  // A zeroed but correct-length ML-DSA key does not throw in noble; it must still be false.
  await mustReturnFalse("zeroed correct-length ML-DSA public key returns false", { ed: verifier.ed, mldsa: new Uint8Array(2592) }, hybridMsg, hybridSig);
  // A wrong-length Ed25519 public key makes Web Crypto importKey reject; must be false.
  await mustReturnFalse("short Ed25519 public key returns false, not throw", { ed: new Uint8Array(10), mldsa: verifier.mldsa }, hybridMsg, hybridSig);
  // A truncated signature (ML-DSA half too short for noble) must be false, not throw.
  const truncatedSig = hybridSig.subarray(0, 64 + 10);
  await mustReturnFalse("truncated ML-DSA signature half returns false, not throw", verifier, hybridMsg, truncatedSig);
  // Sanity: the well-formed verifier + signature still verifies true (the guard did not
  // turn a real verification into a false negative).
  ok("well-formed hybrid verify still returns true after the guard", await hybridVerify(verifier, hybridMsg, hybridSig));

  // -----------------------------------------------------------------------
  // Summary
  // -----------------------------------------------------------------------
  console.log(failures === 0 ? "\nML-DSA SEED KAT PASS" : `\n${failures} FAILURE(S)`);
  if (failures > 0) process.exitCode = 1;
  if (failures > 0) process.exit(1);
}

main().catch((e: unknown) => {
  console.error(e);
  process.exit(1);
});
