// Proves the Microsoft Sentinel Content Hub sample-data generator
// (integrations/microsoft-sentinel/sample-data/generate.ts) actually produces what it claims to:
//
//  - one event per member of AUDIT_ACTIONS, in order, including the run-failed action;
//  - a genuine hash chain that verifies against the engine's OWN verifyChain (src/admin/audit.ts),
//    not a re-implementation of the hashing logic that could quietly agree with itself;
//  - the run-failed sample event carries the { kind: "run", runId } target, mirroring run-trigger's
//    existing target shape, not a placeholder;
//  - the COMMITTED sample-events.ndjson file on disk is byte-identical to what generateSampleEvents()
//    produces right now, so a stale committed fixture (regenerated by hand and forgotten, or hand-
//    edited after generation) is a red here rather than a silent drift from the generator.
//
// The acceptance check this file exists to make: the generated file's hash chain verifies against the
// engine's own verifyChain.
//
// Run: node test/validate-sentinel-sample-data.ts

import { readFileSync } from "node:fs";
import { generateSampleEvents, SAMPLE_FILE, toNDJSON } from "../integrations/microsoft-sentinel/sample-data/generate.ts";
import { verifyChain } from "../src/admin/audit.ts";
import { AUDIT_ACTIONS, type AuditEvent } from "../src/admin/audit-types.ts";
// Importing the verdict guard ARMS it: a run that exits without reaching verdictReached below is
// forced to exit 1, so a drained event loop can never read as a clean sweep.
import { verdictReached } from "./lib/verdict-guard.ts";

let failures = 0;
function ok(label: string, cond: boolean): void {
  console.log((cond ? "  ok   " : "  FAIL ") + label);
  if (!cond) failures++;
}

function parseNDJSON(text: string): AuditEvent[] {
  return text
    .split("\n")
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line) as AuditEvent);
}

async function main(): Promise<void> {
  // ---- SECTION 1: the freshly-generated events, in memory ---------------------------------------------
  const events = await generateSampleEvents();
  ok(`generateSampleEvents produced one event for every AUDIT_ACTIONS member (${AUDIT_ACTIONS.length})`, events.length === AUDIT_ACTIONS.length);
  ok("events are seq 1..N, contiguous from genesis", events.every((e, i) => e.seq === i + 1));
  ok(
    "every AUDIT_ACTIONS member is covered exactly once, in AUDIT_ACTIONS order",
    events.map((e) => e.action).join(",") === AUDIT_ACTIONS.join(","),
  );

  const runFailed = events.find((e) => e.action === "run-failed");
  ok("run-failed is present in the sample data", runFailed !== undefined);
  ok(
    'run-failed carries the { kind: "run", runId } target (mirroring run-trigger)',
    runFailed !== undefined && runFailed.target.kind === "run" && typeof (runFailed.target as { runId?: unknown }).runId === "string",
  );
  ok("run-failed has no human actor (actorMethod engine, actorEmail null)", runFailed !== undefined && runFailed.actorMethod === "engine" && runFailed.actorEmail === null);
  ok('run-failed is recorded with outcome "failed"', runFailed !== undefined && runFailed.outcome === "failed");

  // ---- SECTION 2: the acceptance check itself -- verifyChain over the FRESH events ----------------------
  const freshVerdict = await verifyChain(events);
  ok("THE ACCEPTANCE CHECK: the freshly-generated chain verifies against the engine's own verifyChain (intact:true)", freshVerdict.intact === true);
  ok(`verifyChain checked through the true head (seq ${events.length})`, freshVerdict.checkedThrough === events.length);

  // A tampered copy must NOT verify, so the check above is not vacuously true against a verifier that
  // accepts anything (the same negative-control discipline test/validate-audit-chain.ts uses).
  const tampered = events.map((e) => ({ ...e }));
  const tamperedTarget = tampered[5]!;
  tampered[5] = { ...tamperedTarget, outcome: tamperedTarget.outcome === "success" ? "failed" : "success" };
  const tamperedVerdict = await verifyChain(tampered);
  ok("negative control: verifyChain DOES detect a tampered entry (intact:false)", tamperedVerdict.intact === false && tamperedVerdict.brokenAt === tampered[5]!.seq);

  // ---- SECTION 3: the COMMITTED file on disk, read back exactly as a consumer would ---------------------
  let committedText: string | undefined;
  try {
    committedText = readFileSync(SAMPLE_FILE, "utf8");
  } catch {
    committedText = undefined;
  }
  ok(`the committed NDJSON file exists at ${SAMPLE_FILE}`, committedText !== undefined);

  if (committedText !== undefined) {
    const committedEvents = parseNDJSON(committedText);
    ok(`the committed file has one line per AUDIT_ACTIONS member (${AUDIT_ACTIONS.length})`, committedEvents.length === AUDIT_ACTIONS.length);

    const committedVerdict = await verifyChain(committedEvents);
    ok("THE ACCEPTANCE CHECK, restated against the COMMITTED file: its hash chain verifies against verifyChain", committedVerdict.intact === true);
    ok(`the committed file's chain checks through its true head (seq ${committedEvents.length})`, committedVerdict.checkedThrough === committedEvents.length);

    // The committed file must be what the generator currently produces, byte for byte, not a fixture that
    // was regenerated by hand once and never refreshed after this table changed.
    ok("the committed file is byte-identical to a fresh run of generateSampleEvents (not a stale fixture)", committedText === toNDJSON(events));
  }

  console.log(failures === 0 ? "\nSENTINEL SAMPLE-DATA PASS" : `\n${failures} FAILURE(S)`);
  verdictReached(failures);
  if (failures > 0) process.exit(1);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
