version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule: { interval: weekly }
    groups:
      npm-security-updates:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: weekly }
    groups:
      github-actions-security-updates:
        applies-to: security-updates
        patterns: ["*"]
