// The catalogue (metadata only) for the console's per-surface selection UI, plus the serialisable
// list the discover endpoint returns. This was MOVED VERBATIM out of cf-config-surfaces.ts to keep
// that module a readable size; the behaviour is unchanged. cf-config-surfaces.ts re-exports
// cfConfigCatalogue and surfaceLabel so existing callers keep importing them by name from there.
//
// The console groups Cloudflare configuration surfaces the way it groups KV namespaces / R2
// buckets, so an operator ticks exactly which surfaces a downpipe captures. SURFACE_CATEGORY is
// the grouping, SURFACE_LABEL the human name; cfConfigCatalogue() is the serialisable list the
// discover endpoint returns (the read/write functions never cross the wire). A downpipe stores the
// chosen surface ids in source.include (EXACT ids, the cf-config adapter matches by exact id, not
// prefix); an empty include means "all surfaces".

import type { CfScope, RestoreTier } from "./cf-config-core.ts";
import { CF_CONFIG_SURFACES } from "./cf-config-registry.ts";
import { PROVEN_WRITE_SURFACES } from "./cf-config-write-generated.ts";

const SURFACE_CATEGORY: Record<string, string> = {
  // OpenAPI-gap sweep: the 100 surfaces added by cf-config-registry-gaps.ts and -gaps2.ts.
  // Without these every one renders as a raw slug under "Other", so a third of the public coverage table
  // would read as unfinished.
  "account-custom-page-assets": "Account settings & rules",
  "account-email-routing-rules": "Email & logs",
  "account-email-sending-suppressions": "Email & logs",
  "account-load-balancers": "Traffic & delivery",
  "account-tag-keys": "Account settings & rules",
  "account-waiting-rooms": "Traffic & delivery",
  "acm-total-tls": "TLS & certificates",
  "addressing-leases": "Account network",
  "addressing-services": "Account network",
  "ai-gateway-custom-providers": "Data pipelines",
  "ai-gateway-gateways": "Data pipelines",
  "ai-search-instances": "Data pipelines",
  "ai-search-namespaces": "Data pipelines",
  "ai-search-tokens": "Data pipelines",
  "api-gateway-discovery-settings": "Security & WAF",
  "api-gateway-labels": "Security & WAF",
  "api-gateway-schemas": "Security & WAF",
  "api-gateway-user-schema-hosts": "Security & WAF",
  "browser-extension-config": "Account settings & rules",
  "cache-origin-pq-encryption": "TLS & certificates",
  "cloudflare-one-applications": "Zero Trust",
  "cloudflare-one-integrations": "Zero Trust",
  "d1-databases-config": "Storage & data",
  "data-security-posture-webhooks": "Security & WAF",
  "dcv-delegation": "TLS & certificates",
  "device-policy-default": "Zero Trust",
  "device-policy-fallback-domains": "Zero Trust",
  "device-policy-split-tunnel-exclude": "Zero Trust",
  "device-policy-split-tunnel-include": "Zero Trust",
  "dlp-custom-prompt-topics": "Zero Trust",
  "dlp-data-classes": "Zero Trust",
  "dlp-data-tag-categories": "Zero Trust",
  "dlp-datasets": "Zero Trust",
  "dlp-document-fingerprints": "Zero Trust",
  "dlp-email-rules": "Zero Trust",
  "dlp-entries": "Zero Trust",
  "dlp-profiles": "Zero Trust",
  "dlp-profiles-custom": "Zero Trust",
  "dlp-sensitivity-groups": "Zero Trust",
  "dlp-settings": "Zero Trust",
  "dnssec-zsk": "TLS & certificates",
  "flagship-apps": "Account settings & rules",
  "gateway-audit-ssh-settings": "Zero Trust",
  "gateway-certificates": "Zero Trust",
  "gateway-custom-certificate": "Zero Trust",
  "gateway-egress-cidr-pairs": "Zero Trust",
  "images-variants": "Storage & data",
  "intel-indicator-feeds": "Security & WAF",
  "intel-ip-lists": "Security & WAF",
  "kv-namespaces-config": "Storage & data",
  "magic-bgp-filter-profiles": "Account network",
  "magic-bgp-settings": "Account network",
  "magic-cf-interconnects": "Account network",
  "magic-cf1-sites": "Account network",
  "magic-gre-tunnels": "Account network",
  "magic-ipsec-tunnels": "Account network",
  "magic-static-routes": "Account network",
  "mnm-config": "Account network",
  "mnm-rules": "Account network",
  "origin-tls-client-auth-certificates": "TLS & certificates",
  "origin-tls-client-auth-hostnames": "TLS & certificates",
  "origin-tls-client-auth-settings": "TLS & certificates",
  "registrar-domains": "DNS & core",
  "registrar-registrations": "DNS & core",
  "rum-site-info": "Account settings & rules",
  "schema-validation-hosts": "Security & WAF",
  "schema-validation-operations": "Security & WAF",
  "schema-validation-schemas": "Security & WAF",
  "schema-validation-settings": "Security & WAF",
  "secrets-store-stores": "Storage & data",
  "smart-shield-healthchecks": "Security & WAF",
  "speed-monitored-pages": "Traffic & delivery",
  "stream-live-inputs": "Storage & data",
  "stream-signing-keys": "Storage & data",
  "stream-watermarks": "Storage & data",
  "stream-webhook": "Storage & data",
  "teamnet-routes": "Zero Trust",
  "teamnet-virtual-networks": "Zero Trust",
  "vectorize-indexes-config": "Storage & data",
  "vuln-scanner-credential-sets": "Security & WAF",
  "waf-legacy-packages": "Security & WAF",
  "warp-connector": "Zero Trust",
  "workers-observability-destinations": "Email & logs",
  "workers-observability-metricsexport": "Email & logs",
  "zerotrust-hostname-routes": "Zero Trust",
  "zerotrust-subnets": "Zero Trust",
  "zone-custom-page-assets": "Account settings & rules",
  "zone-logpush-edge-jobs": "Email & logs",
  "zone-setting-aegis": "DNS & core",
  "zone-setting-auto-origin-tls-kex": "DNS & core",
  "zone-setting-csam-scanner": "DNS & core",
  "zone-setting-fonts": "DNS & core",
  "zone-setting-origin-h2-max-streams": "DNS & core",
  "zone-setting-origin-max-http-version": "DNS & core",
  "zone-setting-origin-tls-compliance": "DNS & core",
  "zone-setting-speed-brain": "DNS & core",
  "zone-setting-ssl-automatic-mode": "DNS & core",
  "zone-setting-zaraz-default": "DNS & core",
  "zt-risk-scoring-behaviors": "Zero Trust",
  "zt-risk-scoring-integrations": "Zero Trust",

  dns: "DNS & core", "dns-settings": "DNS & core", "zone-settings": "DNS & core", "managed-headers": "DNS & core", "url-normalization": "DNS & core",
  rulesets: "Security & WAF", "page-rules": "Security & WAF", "firewall-access-rules": "Security & WAF", filters: "Security & WAF", "firewall-rules": "Security & WAF", "page-shield-policies": "Security & WAF",
  "workers-routes": "Traffic & delivery", "load-balancers": "Traffic & delivery", "waiting-rooms": "Traffic & delivery", "spectrum-apps": "Traffic & delivery", "custom-hostnames": "Traffic & delivery", "custom-pages": "Traffic & delivery",
  "certificate-packs": "TLS & certificates", "custom-certificates": "TLS & certificates", "origin-tls-client-auth": "TLS & certificates",
  "email-routing": "Email & logs", logpush: "Email & logs", "account-logpush": "Email & logs",
  "account-settings": "Account settings & rules", "account-rulesets": "Account settings & rules", "account-rule-lists": "Account settings & rules", "account-custom-pages": "Account settings & rules", "account-firewall-access-rules": "Account settings & rules",
  "account-members": "Account access", "account-roles": "Account access",
  "dns-firewall": "Account network", "lb-pools": "Account network", "lb-monitors": "Account network", "address-maps": "Account network", "ip-prefixes": "Account network", "mtls-certificates": "Account network",
  "notification-policies": "Alerting & Turnstile", "notification-webhooks": "Alerting & Turnstile", turnstile: "Alerting & Turnstile",
  "access-apps": "Zero Trust", "access-groups": "Zero Trust", "access-identity-providers": "Zero Trust", "access-service-tokens": "Zero Trust", "access-custom-pages": "Zero Trust", "access-tags": "Zero Trust", "gateway-rules": "Zero Trust", "gateway-lists": "Zero Trust", "gateway-configuration": "Zero Trust", "tunnels-cloudflared": "Zero Trust", "device-posture-rules": "Zero Trust", "device-settings-policies": "Zero Trust",
  "access-reusable-policies": "Account access",
  "access-mtls-certificates": "Account access",
  "access-key-configuration": "Account access",
  "zone-access-apps": "Zero Trust",
  "zone-access-groups": "Zero Trust",
  "zone-access-identity-providers": "Zero Trust",
  "zone-access-service-tokens": "Zero Trust",
  "zone-zero-trust-organization": "Zero Trust",
  "iam-user-groups": "Account access",
  "iam-resource-groups": "Account access",
  "resource-shares": "Account access",
  "api-shield-user-schemas": "Security & WAF",
  "api-shield-operations": "Security & WAF",
  "api-shield-schema-validation-settings": "Security & WAF",
  "api-shield-settings": "Security & WAF",
  "api-shield-token-validation-config": "Security & WAF",
  "api-shield-token-validation-rules": "Security & WAF",
  "api-shield-client-certificates": "TLS & certificates",
  "api-shield-cert-hostname-associations": "TLS & certificates",
  "keyless-certificates": "TLS & certificates",
  "custom-trust-store": "TLS & certificates",
  "universal-ssl-settings": "TLS & certificates",
  "custom-csrs": "TLS & certificates",
  "custom-csrs-account": "TLS & certificates",
  "workers-account-settings": "Account settings & rules",
  "workers-subdomain": "Account settings & rules",
  "access-organizations": "Account access",
  "zt-device-settings": "Zero Trust",
  "zt-connectivity-settings": "Zero Trust",
  "gateway-logging": "Zero Trust",
  "email-routing-addresses": "Email & logs",
  "email-sending-subdomains": "Email & logs",
  "email-dmarc-reports": "Email & logs",
  "email-routing-catch-all": "Email & logs",
  "lb-monitor-groups": "Traffic & delivery",
  "email-security-allow-policies": "Security & WAF",
  "email-security-block-senders": "Security & WAF",
  "email-security-domains": "Security & WAF",
  "email-security-impersonation-registry": "Security & WAF",
  "email-security-sending-domain-restrictions": "Security & WAF",
  "email-security-trusted-domains": "Security & WAF",
  "email-security-url-ignore-patterns": "Security & WAF",
  "device-posture-integrations": "Zero Trust",
  "device-managed-networks": "Zero Trust",
  "device-resilience-disconnect": "Zero Trust",
  "zone-device-policy-certificates": "Zero Trust",
  "advanced-dns-protection-rules": "Security & WAF",
  "advanced-tcp-protection-allowlist": "Security & WAF",
  "advanced-tcp-protection-prefixes": "Security & WAF",
  "advanced-tcp-protection-syn-filters": "Security & WAF",
  "advanced-tcp-protection-syn-rules": "Security & WAF",
  "advanced-tcp-protection-tcp-flow-filters": "Security & WAF",
  "advanced-tcp-protection-tcp-flow-rules": "Security & WAF",
  "advanced-tcp-protection-status": "Security & WAF",
  "device-ip-profiles": "Zero Trust",
  "dls-prefix-bindings": "Account network",
  "calls-apps": "Account settings & rules",
  "calls-turn-keys": "Account settings & rules",
  "moq-relays": "Account settings & rules",
  "realtimekit-apps": "Account settings & rules",
  "logs-explorer-datasets": "Email & logs",
  "account-logs-explorer-datasets": "Email & logs",
  "observability-saved-queries": "Email & logs",
  "logcontrol-cmb-config": "Email & logs",
  "log-retention-flag": "Email & logs",
  "cni-cnis": "Account network",
  "connectivity-services": "Account network",
  "magic-cloud-onramps": "Account network",
  "magic-cloud-providers": "Account network",
  "gateway-locations": "Zero Trust",
  "gateway-proxy-endpoints": "Zero Trust",
  "gateway-pac-files": "Zero Trust",
  "gateway-ssh-ca": "Zero Trust",
  "zone-entity": "DNS & core",
  "zone-hold": "DNS & core",
  "zone-environments": "DNS & core",
  "image-registries": "Account settings & rules",
  "deployment-groups": "Zero Trust",
  "vuln-scanner-target-environments": "Security & WAF",
  "build-tokens": "Account access",
  "notification-silences": "Alerting & Turnstile",
  "ct-alerting": "Alerting & Turnstile",
  "notification-pagerduty-destinations": "Alerting & Turnstile",
  "intel-sinkholes": "Security & WAF",
  "botnet-feed-asn-configs": "Security & WAF",
  "ai-security": "Security & WAF",
  "fraud-detection-settings": "Security & WAF",
  "account-api-tokens": "Account access",
  "rate-limits": "Security & WAF",
  "zone-lockdowns": "Security & WAF",
  "ua-rules": "Security & WAF",
  "dex-rules": "Zero Trust",
  "dex-tests": "Zero Trust",
  "sso-connectors": "Account access",
  "oauth-clients": "Account access",
  "scim-users": "Account access",
  "scim-groups": "Account access",
  "secondary-dns-acls": "DNS & core",
  "secondary-dns-tsigs": "DNS & core",
  "secondary-dns-peers": "DNS & core",
  "secondary-dns-incoming": "DNS & core",
  "secondary-dns-outgoing": "DNS & core",
  "queues": "Account settings & rules",
  "queue-event-subscriptions": "Account settings & rules",
  "workers-for-platforms": "Account settings & rules",
  "account-dns-settings": "DNS & core",
  "dnssec": "DNS & core",
  "waiting-room-settings": "Traffic & delivery",
  "waiting-room-rules": "Traffic & delivery",
  "waiting-room-events": "Traffic & delivery",
  "web-analytics-sites": "Account settings & rules",
  "zone-rum": "Traffic & delivery",
  "account-rule-list-items": "Account settings & rules",
  "cloudforce-one-rules": "Account settings & rules",
  "healthchecks": "Traffic & delivery",
  "account-endpoint-healthchecks": "Traffic & delivery",
  "pages-projects": "Account settings & rules",
  "pipelines-streams": "Data pipelines",
  "pipelines-sinks": "Data pipelines",
  "pipelines": "Data pipelines",
  "workers-custom-domains": "DNS & core",
  "r2-catalog": "Account settings & rules",
  "r2-catalog-syncs": "Account settings & rules",
  "workflows": "Account settings & rules",
  "tiered-caching": "Traffic & delivery",
  "cache-reserve": "Traffic & delivery",
  "regional-tiered-cache": "Traffic & delivery",
  "smart-tiered-cache": "Traffic & delivery",
  "cache-variants": "Traffic & delivery",
  "origin-cloud-regions": "Traffic & delivery",
  "page-shield-settings": "Security & WAF",
  "smart-shield": "Traffic & delivery",
  "web3-hostnames": "DNS & core",
  "access-mcp-servers": "Account access",
  "access-mcp-portals": "Account access",
  "pay-per-crawl-config": "Security & WAF",
  "pay-per-crawl-crawler-stripe": "Account settings & rules",
  "pay-per-crawl-publisher-stripe": "Account settings & rules",
  "custom-hostname-fallback-origin": "TLS & certificates",
  "zaraz-config": "Traffic & delivery",
  "zaraz-workflow": "Traffic & delivery",
  "regional-hostnames": "DNS & core",
  "account-custom-nameservers": "DNS & core",
  "custom-nameserver-usage": "DNS & core",
  "infrastructure-targets": "Zero Trust",
  "snippets": "Account settings & rules",
  "snippet-rules": "Account settings & rules",
  "container-applications": "Account settings & rules",
  "content-scanning-settings": "Security & WAF",
  "content-scanning-expressions": "Security & WAF",
  "leaked-credential-checks": "Security & WAF",
  "leaked-credential-detections": "Security & WAF",
  "dns-internal-views": "DNS & core",
  "argo-smart-routing": "Traffic & delivery",
  "security-txt": "Security & WAF",
  "bot-management": "Security & WAF",
  "cloud-connector-rules": "Traffic & delivery",
  "google-tag-gateway": "DNS & core",
  "hyperdrive-configs": "Storage & data", vectorize: "Storage & data", "r2-bucket-config": "Storage & data", "durable-objects-namespaces": "Storage & data",
};
const SURFACE_LABEL: Record<string, string> = {
  // OpenAPI-gap sweep.
  "account-custom-page-assets": "Account custom page assets",
  "account-email-routing-rules": "Account email routing rules",
  "account-email-sending-suppressions": "Account email sending suppressions",
  "account-load-balancers": "Account load balancers",
  "account-tag-keys": "Account tag keys",
  "account-waiting-rooms": "Account waiting rooms",
  "acm-total-tls": "ACM total TLS",
  "addressing-leases": "Addressing leases",
  "addressing-services": "Addressing services",
  "ai-gateway-custom-providers": "AI gateway custom providers",
  "ai-gateway-gateways": "AI gateway gateways",
  "ai-search-instances": "AI search instances",
  "ai-search-namespaces": "AI search namespaces",
  "ai-search-tokens": "AI search tokens",
  "api-gateway-discovery-settings": "API gateway discovery settings",
  "api-gateway-labels": "API gateway labels",
  "api-gateway-schemas": "API gateway schemas",
  "api-gateway-user-schema-hosts": "API gateway user schema hosts",
  "browser-extension-config": "Browser extension configuration",
  "cache-origin-pq-encryption": "Cache origin post-quantum encryption",
  "cloudflare-one-applications": "Cloudflare one applications",
  "cloudflare-one-integrations": "Cloudflare one integrations",
  "d1-databases-config": "D1 database configuration",
  "data-security-posture-webhooks": "Data security posture webhooks",
  "dcv-delegation": "DCV delegation",
  "device-policy-default": "WARP device policy",
  "device-policy-fallback-domains": "WARP fallback domains",
  "device-policy-split-tunnel-exclude": "Split tunnel exclude list",
  "device-policy-split-tunnel-include": "Split tunnel include list",
  "dlp-custom-prompt-topics": "DLP custom prompt topics",
  "dlp-data-classes": "DLP data classes",
  "dlp-data-tag-categories": "DLP data tag categories",
  "dlp-datasets": "DLP datasets",
  "dlp-document-fingerprints": "DLP document fingerprints",
  "dlp-email-rules": "DLP email rules",
  "dlp-entries": "DLP entries",
  "dlp-profiles": "DLP profiles",
  "dlp-profiles-custom": "DLP custom profiles",
  "dlp-sensitivity-groups": "DLP sensitivity groups",
  "dlp-settings": "DLP settings",
  "dnssec-zsk": "DNSSEC zsk",
  "flagship-apps": "Flagship apps",
  "gateway-audit-ssh-settings": "Gateway audit ssh settings",
  "gateway-certificates": "Gateway certificates",
  "gateway-custom-certificate": "Gateway custom certificate",
  "gateway-egress-cidr-pairs": "Gateway egress cidr pairs",
  "images-variants": "Images variants",
  "intel-indicator-feeds": "Intel indicator feeds",
  "intel-ip-lists": "Intel ip lists",
  "kv-namespaces-config": "KV namespace configuration",
  "magic-bgp-filter-profiles": "Magic BGP filter profiles",
  "magic-bgp-settings": "Magic BGP settings",
  "magic-cf-interconnects": "Cloudflare interconnects",
  "magic-cf1-sites": "Magic Transit sites",
  "magic-gre-tunnels": "Magic GRE tunnels",
  "magic-ipsec-tunnels": "Magic IPsec tunnels",
  "magic-static-routes": "Magic static routes",
  "mnm-config": "Magic Network Monitoring config",
  "mnm-rules": "Magic Network Monitoring rules",
  "origin-tls-client-auth-certificates": "Origin TLS client auth certificates",
  "origin-tls-client-auth-hostnames": "Origin TLS client auth hostnames",
  "origin-tls-client-auth-settings": "Origin TLS client auth settings",
  "registrar-domains": "Registrar domains",
  "registrar-registrations": "Registrar registrations",
  "rum-site-info": "Web Analytics sites",
  "schema-validation-hosts": "Schema validation hosts",
  "schema-validation-operations": "Schema validation operations",
  "schema-validation-schemas": "Schema validation schemas",
  "schema-validation-settings": "Schema validation settings",
  "secrets-store-stores": "Secrets Store stores",
  "smart-shield-healthchecks": "Smart shield healthchecks",
  "speed-monitored-pages": "Speed monitored pages",
  "stream-live-inputs": "Stream live inputs",
  "stream-signing-keys": "Stream signing keys",
  "stream-watermarks": "Stream watermarks",
  "stream-webhook": "Stream webhook",
  "teamnet-routes": "Tunnel routes",
  "teamnet-virtual-networks": "Tunnel virtual networks",
  "vectorize-indexes-config": "Vectorize indexes config",
  "vuln-scanner-credential-sets": "Vulnerability scanner credential sets",
  "waf-legacy-packages": "Legacy WAF packages",
  "warp-connector": "WARP connectors",
  "workers-observability-destinations": "Workers observability destinations",
  "workers-observability-metricsexport": "Workers observability metricsexport",
  "zerotrust-hostname-routes": "Zerotrust hostname routes",
  "zerotrust-subnets": "Zerotrust subnets",
  "zone-custom-page-assets": "Zone custom page assets",
  "zone-logpush-edge-jobs": "Zone logpush edge jobs",
  "zone-setting-aegis": "Zone setting: aegis",
  "zone-setting-auto-origin-tls-kex": "Zone setting: auto origin tls kex",
  "zone-setting-csam-scanner": "Zone setting: csam scanner",
  "zone-setting-fonts": "Zone setting: fonts",
  "zone-setting-origin-h2-max-streams": "Zone setting: origin h2 max streams",
  "zone-setting-origin-max-http-version": "Zone setting: origin max http version",
  "zone-setting-origin-tls-compliance": "Zone setting: origin tls compliance",
  "zone-setting-speed-brain": "Zone setting: speed brain",
  "zone-setting-ssl-automatic-mode": "Zone setting: ssl automatic mode",
  "zone-setting-zaraz-default": "Zone setting: zaraz default",
  "zt-risk-scoring-behaviors": "Zero Trust risk behaviours",
  "zt-risk-scoring-integrations": "Zero Trust risk integrations",

  dns: "DNS records", "dns-settings": "DNS settings", "zone-settings": "Zone settings", "managed-headers": "Managed transform headers", "url-normalization": "URL normalization",
  rulesets: "WAF & rulesets (zone)", "page-rules": "Page rules", "firewall-access-rules": "Firewall access rules", filters: "Filters (legacy)", "firewall-rules": "Firewall rules (legacy)", "page-shield-policies": "Page Shield policies",
  "workers-routes": "Workers routes", "load-balancers": "Load balancers (zone)", "waiting-rooms": "Waiting rooms", "spectrum-apps": "Spectrum apps", "custom-hostnames": "Custom hostnames (SaaS)", "custom-pages": "Custom error pages",
  "certificate-packs": "Certificate packs", "custom-certificates": "Custom certificates", "origin-tls-client-auth": "Authenticated origin pulls",
  "email-routing": "Email routing", logpush: "Logpush jobs (zone)", "account-logpush": "Logpush jobs (account)",
  "account-settings": "Account settings", "account-rulesets": "WAF & rulesets (account)", "account-rule-lists": "Rule lists", "account-custom-pages": "Custom pages (account)", "account-firewall-access-rules": "Firewall access rules (account)",
  "account-members": "Account members", "account-roles": "Account roles",
  "dns-firewall": "DNS Firewall", "lb-pools": "Load balancer pools", "lb-monitors": "Load balancer monitors", "address-maps": "Address maps", "ip-prefixes": "IP prefixes", "mtls-certificates": "mTLS certificates",
  "notification-policies": "Notification policies", "notification-webhooks": "Notification webhooks", turnstile: "Turnstile widgets",
  "access-apps": "Access apps", "access-groups": "Access groups", "access-identity-providers": "Access identity providers", "access-service-tokens": "Access service tokens", "access-custom-pages": "Access custom pages", "access-tags": "Access tags", "gateway-rules": "Gateway rules", "gateway-lists": "Gateway lists", "gateway-configuration": "Gateway configuration", "tunnels-cloudflared": "Tunnels (cloudflared)", "device-posture-rules": "Device posture rules", "device-settings-policies": "Device settings policies",
  "access-reusable-policies": "Access reusable policies",
  "access-mtls-certificates": "Access mTLS certificates",
  "access-key-configuration": "Access key configuration",
  "zone-access-apps": "Zone Access applications",
  "zone-access-groups": "Zone Access groups",
  "zone-access-identity-providers": "Zone Access identity providers",
  "zone-access-service-tokens": "Zone Access service tokens",
  "zone-zero-trust-organization": "Zone Zero Trust organization",
  "iam-user-groups": "IAM user groups",
  "iam-resource-groups": "IAM resource groups",
  "resource-shares": "Resource shares",
  "api-shield-user-schemas": "API Shield user schemas",
  "api-shield-operations": "API Shield endpoint operations",
  "api-shield-schema-validation-settings": "API Shield schema validation settings",
  "api-shield-settings": "API Shield settings",
  "api-shield-token-validation-config": "API Shield token validation config",
  "api-shield-token-validation-rules": "API Shield token validation rules",
  "api-shield-client-certificates": "API Shield client certificates (mTLS)",
  "api-shield-cert-hostname-associations": "API Shield mTLS hostname associations",
  "keyless-certificates": "Keyless SSL configurations",
  "custom-trust-store": "Custom origin trust store (ACM)",
  "universal-ssl-settings": "Universal SSL settings",
  "custom-csrs": "Custom CSRs (zone)",
  "custom-csrs-account": "Custom CSRs (account)",
  "workers-account-settings": "Workers account settings",
  "workers-subdomain": "Workers subdomain",
  "access-organizations": "Zero Trust organization",
  "zt-device-settings": "Zero Trust device settings",
  "zt-connectivity-settings": "Zero Trust connectivity settings",
  "gateway-logging": "Gateway logging settings",
  "email-routing-addresses": "Email Routing destination addresses",
  "email-sending-subdomains": "Email Sending subdomains",
  "email-dmarc-reports": "Email DMARC report configuration",
  "email-routing-catch-all": "Email Routing catch-all rule",
  "lb-monitor-groups": "LB monitor groups",
  "email-security-allow-policies": "Email Security allow policies",
  "email-security-block-senders": "Email Security blocked senders",
  "email-security-domains": "Email Security protected domains",
  "email-security-impersonation-registry": "Email Security impersonation registry",
  "email-security-sending-domain-restrictions": "Email Security sending domain restrictions",
  "email-security-trusted-domains": "Email Security trusted domains",
  "email-security-url-ignore-patterns": "Email Security URL ignore patterns",
  "device-posture-integrations": "Device posture integrations",
  "device-managed-networks": "Device managed networks",
  "device-resilience-disconnect": "Global WARP override (resilience)",
  "zone-device-policy-certificates": "Zone device cert provisioning",
  "advanced-dns-protection-rules": "Advanced DNS Protection rules",
  "advanced-tcp-protection-allowlist": "Advanced TCP Protection allowlist",
  "advanced-tcp-protection-prefixes": "Advanced TCP Protection prefixes",
  "advanced-tcp-protection-syn-filters": "SYN Protection filters",
  "advanced-tcp-protection-syn-rules": "SYN Protection rules",
  "advanced-tcp-protection-tcp-flow-filters": "TCP Flow Protection filters",
  "advanced-tcp-protection-tcp-flow-rules": "TCP Flow Protection rules",
  "advanced-tcp-protection-status": "Advanced TCP Protection status",
  "device-ip-profiles": "Device IP profiles",
  "dls-prefix-bindings": "DLS regional-services prefix bindings",
  "calls-apps": "Realtime SFU (Calls) apps",
  "calls-turn-keys": "Calls TURN keys (wiring)",
  "moq-relays": "MoQ relays",
  "realtimekit-apps": "RealtimeKit apps",
  "logs-explorer-datasets": "Log Explorer datasets (zone)",
  "account-logs-explorer-datasets": "Log Explorer datasets (account)",
  "observability-saved-queries": "Workers Observability saved queries",
  "logcontrol-cmb-config": "Log Control CMB (Customer Metadata Boundary) config",
  "log-retention-flag": "Zone log-retention flag",
  "cni-cnis": "Network Interconnect CNIs",
  "connectivity-services": "Workers VPC connectivity services",
  "magic-cloud-onramps": "Magic Cloud on-ramps",
  "magic-cloud-providers": "Cloud Integration providers",
  "gateway-locations": "Gateway locations",
  "gateway-proxy-endpoints": "Gateway proxy endpoints",
  "gateway-pac-files": "Gateway PAC files",
  "gateway-ssh-ca": "Gateway SSH certificate authorities",
  "zone-entity": "Zone details",
  "zone-hold": "Zone hold",
  "zone-environments": "Zone environments",
  "image-registries": "Container image registries",
  "deployment-groups": "Device deployment groups",
  "vuln-scanner-target-environments": "Vulnerability scanner target environments",
  "build-tokens": "Workers Builds tokens",
  "notification-silences": "Notification silences",
  "ct-alerting": "Certificate Transparency alerting subscription",
  "notification-pagerduty-destinations": "PagerDuty notification destinations",
  "intel-sinkholes": "Intel sinkholes",
  "botnet-feed-asn-configs": "Botnet Threat Feed ASN subscriptions",
  "ai-security": "AI Security for Apps (settings + custom topics)",
  "fraud-detection-settings": "Fraud Detection settings",
  "account-api-tokens": "Account API tokens",
  "rate-limits": "Rate limits (legacy)",
  "zone-lockdowns": "Zone Lockdown rules",
  "ua-rules": "User Agent Blocking rules",
  "dex-rules": "DEX rules",
  "dex-tests": "Device DEX tests",
  "sso-connectors": "SSO connectors",
  "oauth-clients": "OAuth clients",
  "scim-users": "SCIM users",
  "scim-groups": "SCIM groups",
  "secondary-dns-acls": "Secondary DNS ACLs",
  "secondary-dns-tsigs": "Secondary DNS TSIG keys",
  "secondary-dns-peers": "Secondary DNS peers",
  "secondary-dns-incoming": "Secondary (incoming) zone transfer config",
  "secondary-dns-outgoing": "Primary (outgoing) zone transfer config",
  "queues": "Queues (definitions + consumers)",
  "queue-event-subscriptions": "Queue event subscriptions",
  "workers-for-platforms": "Workers for Platforms (dispatch namespaces + script settings)",
  "account-dns-settings": "Account DNS settings",
  "dnssec": "DNSSEC configuration",
  "waiting-room-settings": "Waiting Room zone settings",
  "waiting-room-rules": "Waiting Room bypass rules",
  "waiting-room-events": "Waiting Room scheduled events",
  "web-analytics-sites": "Web Analytics sites & rules",
  "zone-rum": "Zone RUM (Web Analytics) toggle",
  "account-rule-list-items": "Rules list items",
  "cloudforce-one-rules": "Cloudforce One custom rules",
  "healthchecks": "Health checks",
  "account-endpoint-healthchecks": "Endpoint health checks",
  "pages-projects": "Pages projects",
  "pipelines-streams": "Pipelines ingest streams",
  "pipelines-sinks": "Pipelines sinks",
  "pipelines": "Pipelines",
  "workers-custom-domains": "Workers custom domains",
  "r2-catalog": "R2 Data Catalogs",
  "r2-catalog-syncs": "R2 Catalog Syncs",
  "workflows": "Workflows",
  "tiered-caching": "Tiered Caching",
  "cache-reserve": "Cache Reserve",
  "regional-tiered-cache": "Regional Tiered Cache",
  "smart-tiered-cache": "Smart Tiered Cache",
  "cache-variants": "Cache Variants",
  "origin-cloud-regions": "Origin cloud region mappings",
  "page-shield-settings": "Page Shield settings",
  "smart-shield": "Smart Shield settings",
  "web3-hostnames": "Web3 gateway hostnames",
  "access-mcp-servers": "Access MCP servers",
  "access-mcp-portals": "Access MCP portals",
  "pay-per-crawl-config": "Pay Per Crawl config",
  "pay-per-crawl-crawler-stripe": "Pay Per Crawl crawler Stripe wiring",
  "pay-per-crawl-publisher-stripe": "Pay Per Crawl publisher Stripe wiring",
  "custom-hostname-fallback-origin": "Custom hostname fallback origin",
  "zaraz-config": "Zaraz configuration",
  "zaraz-workflow": "Zaraz workflow",
  "regional-hostnames": "Regional hostnames",
  "account-custom-nameservers": "Account custom nameservers",
  "custom-nameserver-usage": "Zone custom nameserver usage",
  "infrastructure-targets": "Infrastructure access targets",
  "snippets": "Snippets",
  "snippet-rules": "Snippet rules",
  "container-applications": "Container applications",
  "content-scanning-settings": "Content Scanning settings",
  "content-scanning-expressions": "Content Scanning custom expressions",
  "leaked-credential-checks": "Leaked Credential Checks status",
  "leaked-credential-detections": "Leaked Credential custom detections",
  "dns-internal-views": "Internal DNS Views",
  "argo-smart-routing": "Argo Smart Routing",
  "security-txt": "Security.txt",
  "bot-management": "Bot Management",
  "cloud-connector-rules": "Cloud Connector rules",
  "google-tag-gateway": "Google Tag Gateway config",
  "hyperdrive-configs": "Hyperdrive configs", vectorize: "Vectorize indexes (config)", "r2-bucket-config": "R2 bucket settings (lifecycle / lock / CORS)", "durable-objects-namespaces": "Durable Objects namespaces",
};

export interface CfConfigSurfaceMeta {
  id: string;
  label: string;
  category: string;
  scope: CfScope;
  restoreTier: RestoreTier;
  // inBand is TRUE only for a surface a default restore actually writes back: it carries a write() AND
  // its id is in PROVEN_WRITE_SURFACES. This is the only field any consumer may present as a restore
  // promise.
  //
  // It exists because restoreTier was the only signal the catalogue exposed, and restoreTier answers a
  // different question: "could this replay cleanly in principle", not "does downpipes replay it for
  // you". The idempotent tier is several times larger than the in-band set, so a console that renders the tier and
  // nothing else invites a reader to overstate write-back by nearly an order of magnitude. The docs page
  // on this exists specifically to prevent that misreading, and the catalogue was set up to invite it.
  inBand: boolean;
  // available is TRUE for a surface that carries a write() which has NOT passed the live round trip. It
  // is reachable only when an operator names it explicitly and an approver signs a plan hash that
  // includes it (F10). Present it separately or not at all; folding it into inBand would publish a
  // restore promise for writers whose natural key has never been tested against real data.
  available: boolean;
}

export function cfConfigCatalogue(): CfConfigSurfaceMeta[] {
  return CF_CONFIG_SURFACES.map((s) => {
    const hasWriter = typeof s.write === "function";
    return {
      id: s.id,
      label: SURFACE_LABEL[s.id] ?? s.id,
      category: SURFACE_CATEGORY[s.id] ?? "Other",
      scope: s.scope,
      restoreTier: s.restoreTier,
      inBand: hasWriter && PROVEN_WRITE_SURFACES.has(s.id),
      available: hasWriter && !PROVEN_WRITE_SURFACES.has(s.id),
    };
  });
}

// surfaceLabel is the human name for a surface id (the restore diff preview labels each surface).
/** @knipignore Label helper for the built-but-unwired cf-config restore diff-preview (see diffConfig). Wire or remove (P3). */
export function surfaceLabel(id: string): string {
  return SURFACE_LABEL[id] ?? id;
}
